Workflow build-cli.yaml: Add alpine build

diff --git a/.github/workflows/build-cli.yml b/.github/workflows/build-cli.yml
--- a/.github/workflows/build-cli.yml
+++ b/.github/workflows/build-cli.yml
@@ -266,6 +266,117 @@ jobs:
         run: node ./build/bw.js --help
 
 
+  cli-alpine:
+    name: CLI ${{ matrix.os.base }}${{ matrix.os.target_suffix }} - ${{ matrix.license_type.readable }}
+    strategy:
+      matrix:
+        os:
+          [
+            { base: "alpine", distro: "ubuntu-22.04", target_suffix: "" },
+            { base: "alpine", distro: "ubuntu-22.04-arm", target_suffix: "-arm64" },
+          ]
+        license_type:
+          [
+            { build_prefix: "oss", artifact_prefix: "-oss", readable: "open source license" },
+            { build_prefix: "bit", artifact_prefix: "", readable: "commercial license" }
+          ]
+    runs-on: ${{ matrix.os.distro }}
+    container: alpine:3.22
+    needs: setup
+    env:
+      _PACKAGE_VERSION: ${{ needs.setup.outputs.package_version }}
+      _NODE_VERSION: ${{ needs.setup.outputs.node_version }}
+      _WIN_PKG_FETCH_VERSION: 20.11.1
+      _WIN_PKG_VERSION: 3.5
+    permissions:
+      contents: read
+      id-token: write
+
+    steps:
+      - name: Check out repo
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
+
+      - name: Setup Unix Vars
+        run: |
+          echo "LOWER_RUNNER_OS=$(echo $RUNNER_OS | awk '{print tolower($0)}')" >> $GITHUB_ENV
+          echo "SHORT_RUNNER_OS=$(echo $RUNNER_OS | awk '{print substr($0, 1, 3)}' | \
+            awk '{print tolower($0)}')" >> $GITHUB_ENV
+
+      - name: Set up Node
+        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
+        with:
+          cache: 'npm'
+          cache-dependency-path: '**/package-lock.json'
+          node-version: ${{ env._NODE_VERSION }}
+
+      - name: Install
+        run: npm ci
+        working-directory: ./
+
+      - name: Download SDK Artifacts
+        if: ${{ inputs.sdk_branch != '' && needs.setup.outputs.has_secrets == 'true' }}
+        uses: bitwarden/gh-actions/download-artifacts@main
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          workflow: build-wasm-internal.yml
+          workflow_conclusion: success
+          branch: ${{ inputs.sdk_branch }}
+          artifacts: sdk-internal
+          repo: bitwarden/sdk-internal
+          path: ../sdk-internal
+          if_no_artifact_found: fail
+
+      - name: Override SDK
+        if: ${{ inputs.sdk_branch != '' && needs.setup.outputs.has_secrets == 'true' }}
+        working-directory: ./
+        run: |
+          ls -l ../
+          npm link ../sdk-internal
+
+      - name: Build & Package Unix
+        run: npm run dist:${{ matrix.license_type.build_prefix }}:${{ env.SHORT_RUNNER_OS }}${{ matrix.os.target_suffix }} --quiet
+
+      - name: Zip Unix
+        run: |
+          cd ./dist/${{ matrix.license_type.build_prefix }}/${{ env.LOWER_RUNNER_OS }}${{ matrix.os.target_suffix }}
+          zip ../../bw${{ matrix.license_type.artifact_prefix }}-${{ env.LOWER_RUNNER_OS }}${{ matrix.os.target_suffix }}-${{ env._PACKAGE_VERSION }}.zip ./bw
+
+      - name: Version Test
+        run: |
+          unzip "./dist/bw${{ matrix.license_type.artifact_prefix }}-${{ env.LOWER_RUNNER_OS }}${{ matrix.os.target_suffix }}-${{ env._PACKAGE_VERSION }}.zip" -d "./test"
+          testVersion=$(./test/bw -v)
+          echo "version: $_PACKAGE_VERSION"
+          echo "testVersion: $testVersion"
+          if [[ $testVersion != $_PACKAGE_VERSION ]]; then
+            echo "Version test failed."
+            exit 1
+          fi
+
+      - name: Upload unix zip asset
+        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
+        with:
+          name: bw${{ matrix.license_type.artifact_prefix }}-${{ env.LOWER_RUNNER_OS }}${{ matrix.os.target_suffix }}-${{ env._PACKAGE_VERSION }}.zip
+          path: apps/cli/dist/bw${{ matrix.license_type.artifact_prefix }}-${{ env.LOWER_RUNNER_OS }}${{ matrix.os.target_suffix }}-${{ env._PACKAGE_VERSION }}.zip
+          if-no-files-found: error
+
+      # We want to confirm the CLI is runnable using the dependencies defined in `apps/cli/package.json`.
+      - name: Remove node_modules (root)
+        run: rm -rf node_modules
+        working-directory: ./
+
+      - name: Remove package.json (root)
+        run: rm package.json
+        working-directory: ./
+
+      - name: Install (CLI)
+        run: npm i
+
+      - name: Output help
+        run: node ./build/bw.js --help
+
+
   cli-windows:
     name: Windows - ${{ matrix.license_type.readable }}
     strategy:
